version: '3.8'

services:
  frontend:
    build:
      context: ./kopi-fe
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./kopi-fe:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

  backend:
    build:
      context: ./kopi-debate-api
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./kopi-debate-api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./kopi-debate-api/.env 