name: Kopi Debate API CI

on:
  push:
    branches: [ main ]
    paths:
      - 'kopi-debate-api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'kopi-debate-api/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kopi-debate-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Run tests
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python -m pytest tests/

      - name: Build Docker image
        run: |
          docker build -t kopi-debate-api:${{ github.sha }} .

      - name: Save Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker save kopi-debate-api:${{ github.sha }} > ../kopi-debate-api.tar

      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: kopi-debate-api-image
          path: kopi-debate-api.tar
          retention-days: 1
